version: '2'
services:
  nginx:
    image: nginx:1.14.0
    ports:
     - "8080:80"
    volumes:
     - ./src/magento2/:/src/magento2/
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php7.0-fpm
        - db
  php7.0-fpm:
    build: ./php
    volumes:
     - ./src/magento2/:/src/magento2/
     - ./nginx/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  db:
    image: mysql:5.7
    volumes: 
      - ./data:/var/lib/mysql
    environment:
        MYSQL_DATABASE: 'magento2'
        MYSQL_ROOT_PASSWORD: 'admin123'
  varnish:
    image: eeacms/varnish
    ports:
    - "81:6081"
    - "6085:6085"
    depends_on:
    - anon
    - auth
    - download
    environment:
      BACKENDS: "anon auth download"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "admin"
      DASHBOARD_PASSWORD: "admin"
      DASHBOARD_SERVERS: "varnish"
      DASHBOARD_DNS_ENABLED: "true"
  anon:
    image: eeacms/hello
    environment:
      PORT: "8080"
  auth:
    image: eeacms/hello
    environment:
      PORT: "8080"
  download:
    image: eeacms/hello
    environment:
      PORT: "8080"
